workflows:
  ios-capacitor:
    name: Build iOS Capacitor App
    environment:
      vars:
        NODE_VERSION: 20
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the Vite project
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Build Xcode project
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/App.xcarchive \
                     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportOptionsPlist ios/App/exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - ios_output/*.ipa
    publishing:
      email:
        recipients:
          - ton.email@example.com

